---
title: "LIBRO DE CÓDIGO"
author: "Ramos Herrera Aylín & Mendoza De Jesus Jose Alejandro"
date: "8 de junio de 2017"
output: html_document
---

# PROGRAMACIÓN ACTUARIAL 3
## CASO 3

### DESCRIPCIÓN
Dentro de la base de datos, obtenida por la compañía telefónica Samsung proveniente del análisis de los acelerómetros ubicados dentro de sus celulares modelo **Galaxy S**, contiene las variables que describen el comportamiento bajo las diferentes actividades realizadas por el usuario  (específicamente 6), en 3 ejes. Estos están señalados por los vectores *X*,*Y* y *Z*.
Los 30 usuarios registrados para dicho estudio, fueron seleccionados de manera voluntaria contando con edades que oscilan entre los 19 y 48 años. 
Este documento presenta las variables, sus derivaciones así como las actividades utilizadas dentro de este experimento.

### 1.VARIABLES:
     + tBodyAcc-mean()-X 
     + tBodyAcc-mean()-Y          
     + tBodyAcc-mean()-Z          
     + tBodyAcc-std()-X           
     + tBodyAcc-std()-Y           
     + tBodyAcc-std()-Z           
     + tGravityAcc-mean()-X       
     + tGravityAcc-mean()-Y       
     + tGravityAcc-mean()-Z       
     + tGravityAcc-std()-X        
     + tGravityAcc-std()-Y        
     + tGravityAcc-std()-Z       
     + tBodyAccJerk-mean()-X      
     + tBodyAccJerk-mean()-Y      
     + tBodyAccJerk-mean()-Z      
     + tBodyAccJerk-std()-X       
     + tBodyAccJerk-std()-Y       
     + tBodyAccJerk-std()-Z       
     + tBodyGyro-mean()-X         
     + tBodyGyro-mean()-Y         
     + tBodyGyro-mean()-Z         
     + tBodyGyro-std()-X          
     + tBodyGyro-std()-Y          
     + tBodyGyro-std()-Z          
     + tBodyGyroJerk-mean()-X     
     + tBodyGyroJerk-mean()-Y     
     + tBodyGyroJerk-mean()-Z     
     + tBodyGyroJerk-std()-X      
     + tBodyGyroJerk-std()-Y      
     + tBodyGyroJerk-std()-Z      
     + tBodyAccMag-mean()         
     + tBodyAccMag-std()       
     + tGravityAccMag-mean()      
     + tGravityAccMag-std()      
     + tBodyAccJerkMag-mean()     
     + tBodyAccJerkMag-std()      
     + tBodyGyroMag-mean()        
     + tBodyGyroMag-std()     
     + tBodyGyroJerkMag-mean()    
     + tBodyGyroJerkMag-std()     
     + fBodyAcc-mean()-X          
     + fBodyAcc-mean()-Y          
     + fBodyAcc-mean()-Z          
     + fBodyAcc-std()-X           
     + fBodyAcc-std()-Y           
     + fBodyAcc-std()-Z       
     + fBodyAccJerk-mean()-X      
     + fBodyAccJerk-mean()-Y      
     + fBodyAccJerk-mean()-Z      
     + fBodyAccJerk-std()-X       
     + fBodyAccJerk-std()-Y       
     + fBodyAccJerk-std()-Z       
     + fBodyGyro-mean()-X         
     + fBodyGyro-mean()-Y         
     + fBodyGyro-mean()-Z         
     + fBodyGyro-std()-X          
     + fBodyGyro-std()-Y          
     + fBodyGyro-std()-Z          
     + fBodyAccMag-mean()         
     + fBodyAccMag-std()  
     + fBodyBodyAccJerkMag-mean() 
     + fBodyBodyAccJerkMag-std()  
     + fBodyBodyGyroMag-mean()    
     + fBodyBodyGyroMag-std() 
     + fBodyBodyGyroJerkMag-mean()
     + fBodyBodyGyroJerkMag-std()
     
#### 1.1Variaciones:
        + 1)mean(): Promedio
        + 2)std(): Desviación estándar
    
Cabe mencionar que puede observarse la lista completa de variables dentro del documento *features.txt*.

### 2.MOVIMIENTOS:
    + 1.WALKING:Caminar
    + 2.WALKING UPSTAIRS:Subir Escaleras
    + 3.WALKING DOWNSTAIRS:Bajar Escaleras
    + 4.SITTING:Estar Sentado
    + 5.STANDING:Estar parado
    + 6.LAYING:Estar acostado

### 3.RECOLECCIÓN Y LIMPIEZA DE DATOS
+ 1) Unión los datos de test con los de training, para crear un solo conjunto de datos.
+ 2) Extracción únicamente las medidas de media y desviación estándar de cada medición.
+ 3) Renombramiento de actividad para describir los nombres de las actividades en la base de
  datos.
+ 4) Colocación etiquetas apropiadas en la base de datos con nombres de variables que las
  describan.
+ 5) Creación una segunda base de datos independiente con el promedio
  de cada variable para cada actividad y cada sujeto.
  
El archivo principal que contiene el análisis completo, se encuentra bajo la liga.
http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones