---
title: "README"
author: "Ramos Herrera Aylín & Mendoza De Jesus Jose Alejandro"
date: " de junio de 2017"
output: html_document
---

# PROGRAMACIÓN ACTUARIAL 3
## CASO 3
## Reconocimiento de actividad Humana con celulares

### DESCRIPCIÓN
Dentro de la base de datos, obtenida por la compañía telefónica Samsung, contiene las variables que describen el comportamiento bajo las diferentes actividades realizadas por el usuario  (especificamente 6), en 3 ejes. Estos están señalados por los vectores *X*,*Y* y *Z*.

A continuación se da un breve explicación de lo que se obtiene al ejecutar el código "correr_analisis.R"

La primera parte del código tiene como objetivo extraer los datos de "test" y "train", para los respectivos valores de nuestras variables x, y. Una vez realizada la extracción, utilizando "read.table", se procede a unir con "rbind" que devuelve un data frame de una sola columna por cada variable, donde fueron colocados los datos.

    xtest <- read.table("./test/X_test.txt")
    xtrain <- read.table("./train/X_train.txt")
    ytest <- read.table("./test/y_test.txt")
    ytrain <- read.table("./train/y_train.txt")
    x <- rbind(xtest, xtrain)
    y <- rbind(ytest, ytrain)
    
     
Se lee el archivo "features.txt", el cual contiene la lista de todas las caracteríticas estudiadas, como resultado se obtiene un factor, y los niveles de éste son utilizados como nombre de las columnas de x, data frame anteriormente creado.
Se encontró un patrón numerico para recolectar las variables deseadas (aquellas que tuvieran las mdedidas de media y desviación estándar), para el cual se creo un bucle definido bajo varias condiciones para ingresar dentro del conjuntos de variables y seleccionar las requeridas. El patrón consiste en utilizar una sucesión numerica que contenga las respectivas filas dentro del documento "features.txt".

    caracteristicas <- read.table("features.txt")[,2]
    colnames(x)<-as.character(caracteristicas)
    recolector<-c()
    numero=1
    for (i in 1:17){
        if (0<i &&i<=5){
            for (w in 1:6){
                z<-as.character(caracteristicas[numero])
                numero<-numero + 1
                recolector<-c(recolector,z)
            }
            numero<-numero+34
        }
        if (5<i && i<=10){
            for (w in 1:2){
                z<-as.character(caracteristicas[numero])
                numero<-numero + 1
                recolector<-c(recolector,z)
            }
            numero<-numero+11
        }
        if (10<i && i<=13){
            for (w in 1:6){
                z<-as.character(caracteristicas[numero])
                numero<-numero + 1
                recolector<-c(recolector,z)
            }
            numero<-numero+73      
        }
        if (i>13){
            for (w in 1:2){
                z<-as.character(caracteristicas[numero])
                numero<-numero + 1
                recolector<-c(recolector,z)
            }
            numero<-numero+11          
        }
    
    }
    extraccion<-x[recolector]
    

Se procede a dar lectura del archivo de texto "activity_labels", que contiene el nombre  de las actividades que fueron analizadas. Lo que se hizo en esta parte fue tomar el data frame "y" (unión de los datos de test y train), y se tomo como factor, para que los niveles de los que estaba conformado tuvieran relación con los nombres de las actividades, con ello se transformo a "y" por un conjunto de datos que muestra la ocurrencia de las actividades en el estudio. 

    actividades <- levels(read.table("activity_labels.txt")[,2])
    y <- as.factor(y[,1])
    levels(y) <- actividades
    Actividad <- y
    
La última lectura de datos se llevo a cabo para la obtención de los sujetos que participaron en el análisis, para ésto se extrajó los sujetos de tests y train, nuevamente se hizo uso de de un data frame, denominada "Sujetos", para colocar la unión de ambas recolecciones.Al final se creo una tabla con los datos ordenados de la parte 2 y 3, en adción con el data frame "Sujetos", es decir, los resultados de dichas ejecuciones dieron paso a la formación de una tabla final con datos ordenados.

    sujetostest <- read.table("./test/subject_test.txt")
    sujetostrain <- read.table("./train/subject_train.txt")
    Sujetos <- rbind(sujetostest, sujetostrain)
    colnames(Sujetos) <- "Sujetos"
    tabla_final <- cbind(Actividad, extraccion, Sujetos)
    
Como parte final, se requería la manipulación de nuestra tabla final para que de resultado una segunda base de datos que estuvera conformada por el promedio de cada variable por  actividad y  sujeto. Con el fin de alcanzar el objetivo se hizo uso de la función "group_by", que toma una tabla existente y la convierte en una agrupada donde las operaciones se realizan por grupo, sin embargo, para la ejecución de dicha instrucción es necesario mandar a llamar a la librería "dplyr", puesto que nos permite analizar y manipular grandes colecciones de datos.
Una vez obtenida nuestra tabla odenada, se aplica la función "summarise_each"" sobre ésta, aplicando "mean" a las columnas de nuestra base ordenada.

    library(dplyr)
    Datos_ordenados <- tabla_final %>%
                        group_by(Actividad, Sujetos)
                        summarise_each(
                            Datos_ordenados,funs(mean)
                        )

Como resultado se obtiene una base de datos (Datos_ordenados) con los promedios de cada variable ordenados por actividad y sujetos.
